version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:17"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      development-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:27"
      timezone: Europe/Berlin
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - security
