import type { ScryActionName, ScryBudgetProfile, ScryProductDefinition } from "./types.js";

export const SCRY_ORIGIN = "https://scry.solanahub.de";

export const SCRY_PRODUCTS = {
  SCRY_WALLET_QUICK_FLAG: {
    actionName: "SCRY_WALLET_QUICK_FLAG",
    product: "scry_wallet_quick_flag",
    label: "wallet quick-flag evidence",
    inputKind: "wallet",
    routeTemplate: "/x402/wallet/:address/quick-flag",
    subjectField: "address",
    priceUsd: 0.001,
    description:
      "Retrieve Scry's lowest-cost neutral wallet prefilter before deciding whether deeper evidence is warranted.",
    buyerIntent: "Triage one wallet at the lowest catalog cost before choosing deeper evidence.",
    notFor:
      "Do not use when the caller already requires transfers, funding lineage, or combined context.",
    lowerCostAlternative: null,
    moreCompleteAlternative: "SCRY_WALLET_FORENSICS",
    similes: ["SOLANA_WALLET_PREFILTER", "WALLET_QUICK_FLAG", "SCRY_QUICK_FLAG"],
    requiredFields: [
      "status",
      "product",
      "address",
      "in_db",
      "supported",
      "quick_flags",
      "coverage",
      "evidence_pack",
      "agent_decision_support",
      "spend_rationale",
      "methodology",
    ],
  },
  SCRY_WALLET_FORENSICS: {
    actionName: "SCRY_WALLET_FORENSICS",
    product: "scry_wallet_forensics",
    label: "wallet forensics",
    inputKind: "wallet",
    routeTemplate: "/x402/wallet/:address/forensics",
    subjectField: "address",
    priceUsd: 0.05,
    description:
      "Retrieve a neutral Scry evidence dossier for one Solana wallet, including coverage and freshness.",
    buyerIntent:
      "Inspect one wallet's identity, activity, risk evidence, and coverage in a focused dossier.",
    notFor:
      "Do not use for a weekly cohort, a token mint, or a combined transfer-and-lineage bundle.",
    lowerCostAlternative: "SCRY_WALLET_QUICK_FLAG",
    moreCompleteAlternative: "SCRY_WALLET_FULL_CONTEXT_PRO",
    similes: ["SOLANA_WALLET_FORENSICS", "WALLET_EVIDENCE_DOSSIER", "SCRY_FORENSICS"],
    requiredFields: [
      "product",
      "address",
      "in_db",
      "supported",
      "risk_summary",
      "coverage",
      "evidence_pack",
      "agent_decision_support",
      "spend_rationale",
      "methodology",
    ],
  },
  SCRY_WALLET_LINEAGE: {
    actionName: "SCRY_WALLET_LINEAGE",
    product: "scry_wallet_lineage",
    label: "wallet funding lineage",
    inputKind: "wallet",
    routeTemplate: "/x402/wallet/:address/lineage",
    subjectField: "address",
    priceUsd: 0.03,
    description:
      "Retrieve neutral upstream-funder and source-of-funds evidence for one Solana wallet.",
    buyerIntent: "Trace one wallet's upstream funding path and source-of-funds evidence.",
    notFor: "Do not use as a general wallet dossier or launch-relationship analysis.",
    lowerCostAlternative: null,
    moreCompleteAlternative: "SCRY_WALLET_FULL_CONTEXT_PRO",
    similes: ["SOLANA_WALLET_LINEAGE", "WALLET_SOURCE_OF_FUNDS", "SCRY_LINEAGE"],
    requiredFields: [
      "product",
      "address",
      "lineage_available",
      "lineage",
      "coverage",
      "evidence_pack",
      "agent_decision_support",
      "spend_rationale",
      "methodology",
    ],
  },
  SCRY_LAUNCH_WINDOW_CLUSTER: {
    actionName: "SCRY_LAUNCH_WINDOW_CLUSTER",
    product: "scry_launch_window_cluster",
    label: "launch-window cluster evidence",
    inputKind: "wallet",
    routeTemplate: "/x402/wallet/:address/launch-window-cluster",
    subjectField: "address",
    priceUsd: 0.05,
    description:
      "Retrieve neutral launch-window counterparty and relationship-cluster evidence for one Solana wallet.",
    buyerIntent:
      "Inspect one wallet's launch-window counterparties and relationship-cluster evidence.",
    notFor: "Do not use as verified same-block co-execution evidence or as a token-mint dossier.",
    lowerCostAlternative: null,
    moreCompleteAlternative: "SCRY_WALLET_FULL_CONTEXT_PRO",
    similes: ["SOLANA_LAUNCH_CLUSTER", "WALLET_CLUSTER_EVIDENCE", "SCRY_LAUNCH_WINDOW"],
    requiredFields: [
      "status",
      "product",
      "address",
      "supported",
      "execution_window",
      "private_routing_context",
      "relationship_cluster",
      "coverage",
      "evidence_pack",
      "agent_decision_support",
      "spend_rationale",
      "methodology",
    ],
  },
  SCRY_WALLET_FULL_CONTEXT_PRO: {
    actionName: "SCRY_WALLET_FULL_CONTEXT_PRO",
    product: "scry_wallet_full_context_pro",
    label: "full wallet context",
    inputKind: "wallet",
    routeTemplate: "/x402/wallet/:address/full-context-pro",
    subjectField: "address",
    priceUsd: 0.18,
    description:
      "Retrieve Scry's neutral composite wallet context with edge-gap reconciliation and provenance.",
    buyerIntent:
      "Get one combined wallet response when forensics, transfers, lineage, and launch relationships are all required.",
    notFor:
      "Do not use for a narrow prefilter or when one cheaper focused action fully answers the request.",
    lowerCostAlternative: "SCRY_WALLET_FORENSICS",
    moreCompleteAlternative: null,
    similes: ["SOLANA_WALLET_FULL_CONTEXT", "WALLET_INTELLIGENCE_PRO", "SCRY_FULL_CONTEXT"],
    requiredFields: [
      "status",
      "product",
      "address",
      "supported",
      "context_summary",
      "forensics",
      "transfer_tape",
      "funding_lineage",
      "launch_window_cluster",
      "coverage",
      "verification_receipts",
      "evidence_pack",
      "agent_decision_support",
      "spend_rationale",
      "methodology",
    ],
  },
  SCRY_PERSISTENT_WALLETS_WEEKLY: {
    actionName: "SCRY_PERSISTENT_WALLETS_WEEKLY",
    product: "scry_weekly_persistent_wallets",
    label: "weekly persistent-wallet cohort",
    inputKind: "none",
    routeTemplate: "/x402/solana/persistent-wallets/weekly",
    subjectField: null,
    priceUsd: 0.2,
    description:
      "Retrieve Scry's neutral weekly cohort of wallets that persist beyond one-day activity noise.",
    buyerIntent: "Get a parameterless weekly cohort for recurring wallet discovery or monitoring.",
    notFor: "Do not use for evidence about one known wallet or one token mint.",
    lowerCostAlternative: null,
    moreCompleteAlternative: null,
    similes: ["SOLANA_PERSISTENT_WALLETS", "WEEKLY_WALLET_COHORT", "SCRY_PERSISTENT_WALLETS"],
    requiredFields: [
      "product",
      "wallet_count",
      "wallets",
      "evidence_pack",
      "agent_decision_support",
      "spend_rationale",
      "methodology",
    ],
  },
  SCRY_PUMPFUN_LAUNCH_DOSSIER: {
    actionName: "SCRY_PUMPFUN_LAUNCH_DOSSIER",
    product: "scry_pumpfun_launch_dossier",
    label: "Pump.fun launch dossier",
    inputKind: "mint",
    routeTemplate: "/x402/pumpfun/launch-dossier",
    subjectField: "mint",
    priceUsd: 0.3,
    description:
      "Retrieve neutral creator, holder, and launch-window evidence for one Solana token mint.",
    buyerIntent:
      "Inspect one token mint's creator, holder, and launch-window evidence in one dossier.",
    notFor: "Do not use for wallet cohorts or as a trading verdict.",
    lowerCostAlternative: null,
    moreCompleteAlternative: null,
    similes: ["PUMPFUN_LAUNCH_DOSSIER", "SOLANA_MINT_LAUNCH_CONTEXT", "SCRY_TOKEN_DOSSIER"],
    requiredFields: [
      "status",
      "product",
      "mint",
      "supported",
      "launch_preflight",
      "creator_context",
      "launch_window_evidence",
      "coverage",
      "evidence_pack",
      "agent_decision_support",
      "spend_rationale",
      "methodology",
    ],
  },
} as const satisfies Record<ScryActionName, ScryProductDefinition>;

export const SCRY_PRODUCT_LIST = Object.values(SCRY_PRODUCTS);

export const SCRY_BUDGET_PROFILES = {
  PREFLIGHT: {
    perRequestCeilingUsd: 0.05,
    sessionBudgetUsd: 0.2,
    eligibleActions: SCRY_PRODUCT_LIST.filter((product) => product.priceUsd <= 0.05).map(
      (product) => product.actionName,
    ),
    purpose: "Bounded wallet preflight and focused evidence; excludes all products above $0.05.",
  },
  FULL_CATALOG: {
    perRequestCeilingUsd: 0.3,
    sessionBudgetUsd: 0.6,
    eligibleActions: SCRY_PRODUCT_LIST.map((product) => product.actionName),
    purpose:
      "Explicit access to all seven products with room for at most two maximum-price reservations.",
  },
} as const satisfies Record<string, ScryBudgetProfile>;
